services:
  db:
    image: mysql:8.0
    container_name: monitoring_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: monitoring_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  
  web:
    build: .
    container_name: monitoring_falsk
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootdb
      - DB_NAME=monitoring_db
    depends_on:
      - db